title: Your awesome site name
copyright_time: 2015-2020
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_subtitle:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_subtitle: true # set true to show subtitle on the homepage

permalink: /:title.html

# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
glance:
  date_format: "%Y-%m-%d"

# Build settings
theme: glance

plugins:
 - jekyll-feed
 - jekyll-seo-tag
#  - jekyll-paginate
